app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect, url_for
from wtforms import Form, StringField, TextAreaField
from flask_security import login_required

from app import db
from models import Post


posts = Blueprint("posts", __name__,
                  template_folder="templates",
                  static_folder="static")


class PostForm(Form):
    title = StringField("Title")
    body = TextAreaField("Body")


@posts.route("/", methods=["POST", "GET"])
@login_required
def index():
    if request.method == "POST":
        title = request.form.get("title")
        body = request.form.get("body")
        if title and body:
            try:
                post = Post(title=title, body=body)
                db.session.add(post)
                db.session.commit()
            except Exception as err:
                print(err)

            return redirect(url_for("blogs"))

    return render_template("posts/index.html")


@posts.route("/1", methods=["POST", "GET"])
@login_required
def create_post():
    if request.method == "POST":
        title = request.form.get("title")
        body = request.form.get("body")
        if title and body:
            try:
                post = Post(title=title, body=body)
                db.session.add(post)
                db.session.commit()
            except Exception as err:
                print(err)

            return redirect(url_for("blogs"))

    form = PostForm()
    return render_template("posts/create_post.html", form=form)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content %}
    <head>
        <link rel="stylesheet" href="{{ url_for('posts.static', filename='bootstrap.css') }}">
    </head>
    <h1>New post</h1>
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        {% for field in form %}
            <div class="form-group">
                {{ field.label() }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}
        <button type="submit" class="create">Опубликовать</button>
    </form>
{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}


{% block title %}
    Создание блога
{% endblock %}

{% block content %}
    <head>
    <link rel="stylesheet" href="{{ url_for('posts.static', filename='style.css') }}">
    </head>
    <body>
        <h1>Создание страницы</h1>
        <form action="http://localhost:5000/create_blog/" method="POST">
            <p><input type="text" class="title" name="title"></p>
            <p><textarea class="body" name="body"></textarea></p>
            <p><button type="submit" class="create">Опубликовать</button></p>
        </form>
    </body>
{% endblock %}